version: '3.8'

networks:
  default:

services:
  db:
    restart: unless-stopped
    image: mysql:5.7
    container_name: sbms
    ports:
    - 3306:3306
    volumes:
    - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sbms

  postgres:
    restart: unless-stopped
    image: postgres:alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - "./.data/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
      POSTGRES_USER: user