version: '3.8'

networks:
  default:

services:
  db:
    image: mysql:5.7
    container_name: sbms
    ports:
    - 3306:3306
    volumes:
    - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sbms